#pragma config(Sensor, S2,     ir,         sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "/ref/auto_ref.h"

#include "drivers/hitechnic-irseeker-v2.h"


task main()
{

while(true) {
	print(HTIRS2readDCDir(ir));
}

}
